use crate::mcp::client::HttpClientFactory;
use crate::mcp::types::HandlerResult;

struct CdnSignature {
    name: &'static str,
    header_checks: &'static [(&'static str, &'static str)], // (header_name, contains_value)
    ip_ranges_first_octet: &'static [u8],
}

const CDN_SIGNATURES: &[CdnSignature] = &[
    CdnSignature {
        name: "Cloudflare",
        header_checks: &[
            ("server", "cloudflare"),
            ("cf-ray", ""),
            ("cf-cache-status", ""),
            ("cf-request-id", ""),
        ],
        ip_ranges_first_octet: &[104, 172, 103, 131, 141, 108, 162, 190, 188, 197],
    },
    CdnSignature {
        name: "BunnyCDN",
        header_checks: &[
            ("server", "BunnyCDN"),
            ("cdn-pullzone", ""),
            ("cdn-requestid", ""),
            ("cdn-cache", ""),
            ("cdn-proxyver", ""),
        ],
        ip_ranges_first_octet: &[],
    },
    CdnSignature {
        name: "CloudFront",
        header_checks: &[
            ("x-amz-cf-id", ""),
            ("x-amz-cf-pop", ""),
            ("x-cache", "cloudfront"),
            ("via", "cloudfront"),
            ("server", "CloudFront"),
        ],
        ip_ranges_first_octet: &[13, 52, 54, 99, 143, 204],
    },
    CdnSignature {
        name: "Akamai",
        header_checks: &[
            ("x-akamai-transformed", ""),
            ("server", "AkamaiGHost"),
            ("x-akamai-request-id", ""),
        ],
        ip_ranges_first_octet: &[23, 2, 184],
    },
    CdnSignature {
        name: "Fastly",
        header_checks: &[
            ("x-served-by", "cache-"),
            ("x-cache", ""),
            ("x-fastly-request-id", ""),
            ("via", "varnish"),
        ],
        ip_ranges_first_octet: &[151, 199],
    },
    CdnSignature {
        name: "Sucuri",
        header_checks: &[("server", "Sucuri"), ("x-sucuri-id", ""), ("x-sucuri-cache", "")],
        ip_ranges_first_octet: &[],
    },
    CdnSignature {
        name: "Imperva/Incapsula",
        header_checks: &[("x-iinfo", ""), ("x-cdn", "Imperva"), ("server", "Incapsula")],
        ip_ranges_first_octet: &[],
    },
];

struct WafSignature {
    name: &'static str,
    response_patterns: &'static [&'static str], // body/header patterns
    status_codes: &'static [u16],
}

const WAF_SIGNATURES: &[WafSignature] = &[
    WafSignature {
        name: "Cloudflare WAF",
        response_patterns: &["cf-chl-bypass", "Attention Required!", "cloudflare", "Ray ID:", "cf-mitigated"],
        status_codes: &[403, 503, 1020],
    },
    WafSignature {
        name: "Bunny Shield",
        response_patterns: &["bunny", "BunnyCDN", "Bunny Shield"],
        status_codes: &[403, 429],
    },
    WafSignature {
        name: "AWS WAF",
        response_patterns: &["awselb", "x-amzn-RequestId", "AWSALB"],
        status_codes: &[403],
    },
    WafSignature {
        name: "ModSecurity",
        response_patterns: &["ModSecurity", "NOYB", "mod_security"],
        status_codes: &[403, 406],
    },
    WafSignature {
        name: "Wordfence",
        response_patterns: &["wordfence", "wfPage", "This response was generated by Wordfence"],
        status_codes: &[403, 503],
    },
];

fn get_bypass_strategies(cdn_name: &str) -> Vec<serde_json::Value> {
    let mut strategies = Vec::new();

    strategies.push(serde_json::json!({
        "id": "origin_discovery",
        "name": "Origin IP Discovery",
        "description": "Find the real origin IP behind the CDN to bypass all edge protections",
        "techniques": [
            {"method": "dns_history", "tool": "dns_resolve", "detail": "Check historical DNS records via SecurityTrails, ViewDNS for pre-CDN IP"},
            {"method": "subdomain_enum", "tool": "discover_subdomains", "detail": "Find subdomains (dev, staging, mail, ftp) not proxied through CDN"},
            {"method": "ssl_cert_search", "tool": "crtsh_search", "detail": "Search certificate transparency logs for origin certs on direct IPs"},
            {"method": "email_headers", "detail": "Trigger a password reset email, check Received: headers for origin IP"},
            {"method": "favicon_hash", "tool": "favicon_hash", "detail": "Hash the favicon and search Shodan/Censys for servers with same hash"},
            {"method": "ssrf_probe", "detail": "If SSRF exists, make the server connect to your OAST server to reveal its IP"},
        ]
    }));

    strategies.push(serde_json::json!({
        "id": "header_manipulation",
        "name": "Header-Based WAF Evasion",
        "techniques": [
            {"method": "content_type_switch", "detail": "Change Content-Type to text/plain, multipart/form-data, or application/xml — WAF may not inspect these"},
            {"method": "encoding_bypass", "detail": "Use Transfer-Encoding: chunked to split payloads across chunks"},
            {"method": "method_override", "detail": "Add X-HTTP-Method-Override: PUT/DELETE/PATCH to a POST request"},
            {"method": "host_header_injection", "detail": "Send requests with modified Host header to reach origin directly"},
            {"method": "xff_spoof", "detail": "Add X-Forwarded-For: 127.0.0.1 to appear as internal traffic"},
            {"method": "case_variation", "detail": "Use mixed case in paths: /Api/V1/UsErS instead of /api/v1/users"},
        ]
    }));

    strategies.push(serde_json::json!({
        "id": "payload_obfuscation",
        "name": "Payload Obfuscation",
        "techniques": [
            {"method": "double_url_encode", "detail": "Double-encode special chars: ' → %27 → %2527"},
            {"method": "unicode_escape", "detail": "Use Unicode: <script> → \\u003cscript\\u003e"},
            {"method": "comment_insertion", "detail": "SQL: SEL/**/ECT, UN/**/ION, OR/**/DER"},
            {"method": "null_byte", "detail": "Insert %00 to terminate string processing early"},
            {"method": "json_structure_abuse", "detail": "Wrap payloads in nested JSON arrays/objects the WAF can't parse"},
            {"method": "parameter_pollution", "detail": "Send same param multiple times: ?id=1&id=UNION+SELECT"},
        ]
    }));

    strategies.push(serde_json::json!({
        "id": "protocol_abuse",
        "name": "Protocol-Level Bypass",
        "techniques": [
            {"method": "http2_downgrade", "detail": "Force HTTP/1.1 — some WAFs only inspect H2 partially"},
            {"method": "request_smuggling", "tool": "detect_smuggling", "detail": "CL.TE or TE.CL desync to smuggle requests past the WAF"},
            {"method": "websocket_upgrade", "detail": "Upgrade to WebSocket to bypass HTTP-layer inspection"},
            {"method": "padding_evasion", "detail": "Pad request body with >8KB of junk data to exceed WAF inspection buffer"},
            {"method": "chunked_body", "detail": "Split payload across chunked transfer-encoding boundaries"},
        ]
    }));

    match cdn_name {
        "Cloudflare" => {
            strategies.push(serde_json::json!({
                "id": "cloudflare_specific",
                "name": "Cloudflare-Specific Bypasses",
                "techniques": [
                    {"method": "cf_ip_ranges", "detail": "Cloudflare IPs: 104.16-31.x.x, 172.64-71.x.x, 103.21-22.x.x — scan for origin outside these"},
                    {"method": "cf_worker_bypass", "detail": "Check if Workers are used — some routes may bypass WAF rules"},
                    {"method": "cf_acme_path", "detail": "Test /.well-known/acme-challenge/ — often excluded from WAF"},
                    {"method": "cf_cache_deception", "detail": "Append /profile.css to API paths to test cache deception"},
                    {"method": "cf_ja3_fingerprint", "detail": "Cloudflare uses JA3/JA4 TLS fingerprinting — use a real browser TLS stack"},
                    {"method": "cf_turnstile_token", "detail": "If Turnstile is active, extract token from browser session"},
                ]
            }));
        }
        "BunnyCDN" => {
            strategies.push(serde_json::json!({
                "id": "bunny_specific",
                "name": "Bunny.net-Specific Bypasses",
                "techniques": [
                    {"method": "bunny_edge_ips", "detail": "Fetch edge IPs from bunnycdn.com/api/system/edgeserverlist — origin is NOT in this list"},
                    {"method": "bunny_origin_shield", "detail": "Origin Shield is a caching layer, NOT a WAF — requests still reach origin"},
                    {"method": "bunny_pullzone_id", "detail": "CDN-PullZone header reveals pullzone ID — use to enumerate other zones"},
                    {"method": "bunny_perma_cache", "detail": "Check Perma-Cache header — MISS responses go directly to origin"},
                    {"method": "bunny_country_block", "detail": "Bunny Shield geo-blocking can be bypassed via VPN/proxy to allowed country"},
                    {"method": "bunny_token_auth", "detail": "If token auth is used, check for expired/weak token validation"},
                ]
            }));
        }
        "CloudFront" => {
            strategies.push(serde_json::json!({
                "id": "cloudfront_specific",
                "name": "CloudFront-Specific Bypasses",
                "techniques": [
                    {"method": "cf_origin_domain", "detail": "CloudFront origins often use *.amazonaws.com or *.elasticbeanstalk.com subdomains"},
                    {"method": "cf_s3_bucket", "detail": "Check if origin is S3 — test s3.amazonaws.com/<bucket> directly"},
                    {"method": "cf_custom_header", "detail": "CloudFront can set custom origin headers — without these, origin may reject"},
                    {"method": "cf_signed_url", "detail": "Check if signed URLs/cookies are used — test with expired signatures"},
                ]
            }));
        }
        _ => {}
    }

    strategies
}

pub async fn handle_analyze_cdn_waf(params: &serde_json::Value) -> HandlerResult {
    let target = params["target"].as_str().ok_or("Missing target URL or domain")?;

    let url = if target.starts_with("http") { target.to_string() } else { format!("https://{}", target) };

    let client = HttpClientFactory::default_client()?;

    let resp = client.get(&url)
        .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36")
        .send().await.map_err(|e| format!("Request failed: {}", e))?;

    let status = resp.status().as_u16();
    let headers: std::collections::HashMap<String, String> = resp
        .headers()
        .iter()
        .map(|(k, v)| (k.as_str().to_lowercase(), v.to_str().unwrap_or("").to_string()))
        .collect();
    let body = resp.text().await.unwrap_or_default();

    let mut detected_cdns: Vec<serde_json::Value> = Vec::new();
    for sig in CDN_SIGNATURES {
        let mut matched_headers: Vec<String> = Vec::new();
        for (header_name, contains_val) in sig.header_checks {
            if let Some(hval) = headers.get(*header_name) {
                if contains_val.is_empty() || hval.to_lowercase().contains(&contains_val.to_lowercase()) {
                    matched_headers.push(format!("{}: {}", header_name, hval));
                }
            }
        }
        if !matched_headers.is_empty() {
            detected_cdns.push(serde_json::json!({
                "name": sig.name,
                "confidence": if matched_headers.len() >= 2 { "high" } else { "medium" },
                "matched_headers": matched_headers,
            }));
        }
    }

    let mut detected_wafs: Vec<serde_json::Value> = Vec::new();
    let waf_probe_url =
        format!("{}/?test=<script>alert(1)</script>&id=1'+OR+1=1--", url.trim_end_matches('/'));
    let waf_resp = client
        .get(&waf_probe_url)
        .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
        .send()
        .await;

    let (waf_status, waf_headers, waf_body) = match waf_resp {
        Ok(r) => {
            let s = r.status().as_u16();
            let h: std::collections::HashMap<String, String> = r
                .headers()
                .iter()
                .map(|(k, v)| (k.as_str().to_lowercase(), v.to_str().unwrap_or("").to_string()))
                .collect();
            let b = r.text().await.unwrap_or_default();
            (s, h, b)
        }
        Err(_) => (0, std::collections::HashMap::new(), String::new()),
    };

    for sig in WAF_SIGNATURES {
        let mut evidence: Vec<String> = Vec::new();
        if sig.status_codes.contains(&waf_status) {
            evidence.push(format!("Blocked with HTTP {}", waf_status));
        }
        for pattern in sig.response_patterns {
            if waf_body.to_lowercase().contains(&pattern.to_lowercase()) {
                evidence.push(format!("Body contains: {}", pattern));
            }
            for (hk, hv) in &waf_headers {
                if hv.to_lowercase().contains(&pattern.to_lowercase()) {
                    evidence.push(format!("Header {}: contains {}", hk, pattern));
                }
            }
        }
        if !evidence.is_empty() {
            detected_wafs.push(serde_json::json!({
                "name": sig.name,
                "confidence": if evidence.len() >= 2 { "high" } else { "medium" },
                "evidence": evidence,
                "waf_probe_status": waf_status,
            }));
        }
    }

    let mut security_headers: Vec<serde_json::Value> = Vec::new();
    let sec_hdrs = [
        "x-frame-options",
        "strict-transport-security",
        "content-security-policy",
        "x-content-type-options",
        "x-xss-protection",
        "referrer-policy",
        "permissions-policy",
        "cross-origin-opener-policy",
        "cross-origin-embedder-policy",
    ];
    for h in &sec_hdrs {
        if let Some(v) = headers.get(*h) {
            security_headers.push(serde_json::json!({"header": h, "value": v}));
        }
    }

    let server = headers.get("server").cloned().unwrap_or_default();
    let powered_by = headers.get("x-powered-by").cloned().unwrap_or_default();

    let parsed = url::Url::parse(&url).ok();
    let domain = parsed.as_ref().and_then(|u| u.host_str()).unwrap_or(target);
    let mut origin_hints: Vec<serde_json::Value> = Vec::new();
    for prefix in &[
        "origin",
        "direct",
        "backend",
        "real",
        "server",
        "origin-www",
        "app",
        "api-direct",
        "internal",
        "raw",
    ] {
        let sub = format!("{}.{}", prefix, domain);
        if let Ok(addrs) = tokio::net::lookup_host(format!("{}:443", sub)).await {
            let ips: Vec<String> = addrs.map(|a| a.ip().to_string()).collect();
            if !ips.is_empty() {
                origin_hints
                    .push(serde_json::json!({"subdomain": sub, "ips": ips, "type": "potential_origin"}));
            }
        }
    }

    let primary_cdn = detected_cdns.first().and_then(|c| c["name"].as_str()).unwrap_or("unknown");
    let bypass_strategies = get_bypass_strategies(primary_cdn);

    let rate_limit = serde_json::json!({
        "limit": headers.get("x-rate-limit-limit").or(headers.get("x-ratelimit-limit")).cloned(),
        "remaining": headers.get("x-rate-limit-remaining").or(headers.get("x-ratelimit-remaining")).cloned(),
        "reset": headers.get("x-rate-limit-reset").or(headers.get("x-ratelimit-reset")).cloned(),
        "retry_after": headers.get("retry-after").cloned(),
    });

    Ok(serde_json::json!({
        "target": url,
        "status": status,
        "server": server,
        "powered_by": powered_by,
        "detected_cdns": detected_cdns,
        "detected_wafs": detected_wafs,
        "is_behind_cdn": !detected_cdns.is_empty(),
        "is_waf_active": !detected_wafs.is_empty(),
        "security_headers": security_headers,
        "rate_limiting": rate_limit,
        "origin_discovery_hints": origin_hints,
        "bypass_strategies": bypass_strategies,
        "all_response_headers": headers,
        "instructions": format!(
            "{}{}{}",
            if !detected_cdns.is_empty() { format!("CDN detected: {}. ", primary_cdn) } else { "No CDN detected. ".to_string() },
            if !detected_wafs.is_empty() { "WAF is active — use bypass_strategies to evade. " } else { "No WAF blocking detected. " },
            if !origin_hints.is_empty() { "Origin hints found — try direct-to-origin requests." } else { "No origin subdomains found — try dns_history, crtsh_search, favicon_hash." }
        ),
    }))
}

pub async fn handle_get_traffic_log(params: &serde_json::Value) -> HandlerResult {
    let since_id = params["since_id"].as_u64().unwrap_or(0);
    let limit = params["limit"].as_u64().unwrap_or(100) as usize;
    let url_filter = params["url_contains"].as_str();
    let method_filter = params["method"].as_str();
    let status_filter = params["status"].as_u64().map(|s| s as u16);
    let min_status = params["min_status"].as_u64().map(|s| s as u16);
    let max_status = params["max_status"].as_u64().map(|s| s as u16);

    let all_entries = crate::mcp::activity::get_mcp_traffic(since_id);

    let filtered: Vec<&crate::mcp::types::McpTrafficEntry> = all_entries
        .iter()
        .filter(|e| {
            if let Some(f) = url_filter {
                if !e.url.to_lowercase().contains(&f.to_lowercase()) {
                    return false;
                }
            }
            if let Some(m) = method_filter {
                if !e.method.eq_ignore_ascii_case(m) {
                    return false;
                }
            }
            if let Some(s) = status_filter {
                if e.status != s {
                    return false;
                }
            }
            if let Some(min) = min_status {
                if e.status < min {
                    return false;
                }
            }
            if let Some(max) = max_status {
                if e.status > max {
                    return false;
                }
            }
            true
        })
        .collect();

    let total = filtered.len();
    let entries: Vec<serde_json::Value> = filtered.iter().rev().take(limit).map(|e| {
        let mut cdn_hint = String::new();
        let headers_lower = e.response_headers.to_lowercase();
        if headers_lower.contains("cf-ray") || headers_lower.contains("server: cloudflare") {
            cdn_hint = "Cloudflare".to_string();
        } else if headers_lower.contains("bunnycdn") || headers_lower.contains("cdn-pullzone") {
            cdn_hint = "BunnyCDN".to_string();
        } else if headers_lower.contains("x-amz-cf-id") || headers_lower.contains("cloudfront") {
            cdn_hint = "CloudFront".to_string();
        }

        let mut findings: Vec<String> = Vec::new();
        let body_lower = e.response_body.to_lowercase();
        if body_lower.contains("token") || body_lower.contains("bearer") || body_lower.contains("jwt") {
            findings.push("Contains auth tokens".to_string());
        }
        if body_lower.contains("password") || body_lower.contains("secret") {
            findings.push("Contains sensitive fields".to_string());
        }
        if e.status == 500 || e.status == 502 || e.status == 503 {
            findings.push(format!("Server error {}", e.status));
        }
        if headers_lower.contains("x-powered-by") {
            findings.push("Technology disclosure via X-Powered-By".to_string());
        }

        serde_json::json!({
            "id": e.id,
            "timestamp": e.timestamp,
            "method": e.method,
            "url": e.url,
            "host": e.host,
            "path": e.path,
            "tls": e.tls,
            "status": e.status,
            "response_length": e.response_length,
            "response_time_ms": e.response_time_ms,
            "mime_type": e.mime_type,
            "source": e.source,
            "cdn_detected": cdn_hint,
            "auto_findings": findings,
            "request_headers": e.request_headers,
            "request_body": if e.request_body.len() > 2000 { format!("{}...", &e.request_body[..2000]) } else { e.request_body.clone() },
            "response_headers": e.response_headers,
            "response_body": if e.response_body.len() > 5000 { format!("{}...", &e.response_body[..5000]) } else { e.response_body.clone() },
        })
    }).collect();

    let auth_count = entries
        .iter()
        .filter(|e| {
            let url = e["url"].as_str().unwrap_or("");
            url.contains("auth") || url.contains("login") || url.contains("token") || url.contains("identity")
        })
        .count();
    let error_count = entries.iter().filter(|e| e["status"].as_u64().unwrap_or(0) >= 400).count();

    Ok(serde_json::json!({
        "entries": entries,
        "total": total,
        "returned": entries.len(),
        "auth_related": auth_count,
        "errors": error_count,
        "source": "mcp_traffic_log",
        "hint": if total == 0 {
            "No traffic recorded yet. Use send_request to make HTTP requests — all traffic is automatically logged here."
        } else {
            "All MCP HTTP requests are logged here with full request/response data including headers and bodies."
        }
    }))
}
