import { useState, useCallback, useEffect } from 'react';
import { KeyRound, BarChart3, CheckCircle, XCircle, Trash2 } from 'lucide-react';
import { useAppStore } from '../../stores';
import './Tokens.css';

interface AnalysisResult {
  entropy: number;
  rating: string;
  tokenCount: number;
  avgLength: number;
  uniqueChars: number;
  charDistribution: { char: string; freq: number; expected: number }[];
  bitAnalysis: number[];
  fipsMonobit: { pass: boolean; ones: number; total: number };
  fipsPoker: { pass: boolean; chi2: number };
  fipsRuns: { pass: boolean; runs: number };
  fipsLongRun: { pass: boolean; longest: number };
  duplicates: number;
  collisionRate: number;
  // v0.3.16 additions:
  encoding: 'hex' | 'base64' | 'base64url' | 'mixed';
  effectiveBits: number;           // log2(unique_tokens) — practical key-space size
  predictedKeyspaceBits: number;   // log2(charset^avgLen) — theoretical max
  charClasses: { alpha: number; digit: number; upper: number; lower: number; special: number; total: number };
  autocorrLag1: number;            // correlation between token[i] and token[i+1]
  nistFreqBlock: { pass: boolean; chi2: number };
}

function shannonEntropy(data: string): number {
  const freq: Record<string, number> = {};
  for (const c of data) freq[c] = (freq[c] || 0) + 1;
  const len = data.length;
  return -Object.values(freq).reduce((sum, f) => {
    const p = f / len;
    return sum + p * Math.log2(p);
  }, 0);
}

function fipsMonobit(bits: number[]): { pass: boolean; ones: number; total: number } {
  const ones = bits.filter(b => b === 1).length;
  const total = bits.length;
  return { pass: ones > total * 0.46 && ones < total * 0.54, ones, total };
}

function fipsPoker(bits: number[]): { pass: boolean; chi2: number } {
  const nibbles: Record<string, number> = {};
  for (let i = 0; i + 3 < bits.length; i += 4) {
    const key = bits.slice(i, i + 4).join('');
    nibbles[key] = (nibbles[key] || 0) + 1;
  }
  const k = Math.floor(bits.length / 4);
  const chi2 = (16 / k) * Object.values(nibbles).reduce((s, f) => s + f * f, 0) - k;
  return { pass: chi2 > 2.16 && chi2 < 46.17, chi2: Math.round(chi2 * 100) / 100 };
}

function fipsRuns(bits: number[]): { pass: boolean; runs: number } {
  let runs = 1;
  for (let i = 1; i < bits.length; i++) if (bits[i] !== bits[i - 1]) runs++;
  return { pass: runs > bits.length * 0.42 && runs < bits.length * 0.58, runs };
}

function fipsLongRun(bits: number[]): { pass: boolean; longest: number } {
  let max = 1, cur = 1;
  for (let i = 1; i < bits.length; i++) {
    if (bits[i] === bits[i - 1]) { cur++; max = Math.max(max, cur); }
    else cur = 1;
  }
  return { pass: max <= 26, longest: max };
}

function toBits(hex: string): number[] {
  return hex.split('').flatMap(c => {
    const n = parseInt(c, 16);
    return isNaN(n) ? [] : [n >> 3 & 1, n >> 2 & 1, n >> 1 & 1, n & 1];
  });
}

// v0.3.16: detect encoding so non-hex tokens (Base64 session IDs, JWT
// segments, custom alphabets) don't silently fall through to all-zero
// bit analysis. We sniff on the full concatenated dataset, not per token,
// to be robust against e.g. mixed Base64 / Base64URL within one batch.
function detectEncoding(s: string): 'hex' | 'base64' | 'base64url' | 'mixed' {
  if (!s) return 'mixed';
  const isHex = /^[0-9a-fA-F]+$/.test(s);
  if (isHex) return 'hex';
  const isB64 = /^[A-Za-z0-9+/=]+$/.test(s);
  if (isB64) return 'base64';
  const isB64url = /^[A-Za-z0-9_\-=]+$/.test(s);
  if (isB64url) return 'base64url';
  return 'mixed';
}

// Translate any string to a stream of bits — preserves what bits were
// actually generated by the RNG instead of restricting to 4 bits / hex
// char. Uses UTF-8 byte expansion as the fallback for arbitrary strings.
function stringToBits(s: string, encoding: 'hex' | 'base64' | 'base64url' | 'mixed'): number[] {
  if (encoding === 'hex') return toBits(s);
  const bytes = (() => {
    try {
      if (encoding === 'base64' || encoding === 'base64url') {
        const norm = (encoding === 'base64url' ? s.replace(/-/g, '+').replace(/_/g, '/') : s)
          .replace(/[^A-Za-z0-9+/=]/g, '');
        const padded = norm + '='.repeat((4 - (norm.length % 4)) % 4);
        const bin = atob(padded);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
      }
      // Mixed/arbitrary — use UTF-8 byte view.
      return new TextEncoder().encode(s);
    } catch {
      return new Uint8Array(0);
    }
  })();
  const bits: number[] = new Array(bytes.length * 8);
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i];
    bits[i * 8 + 0] = (b >> 7) & 1;
    bits[i * 8 + 1] = (b >> 6) & 1;
    bits[i * 8 + 2] = (b >> 5) & 1;
    bits[i * 8 + 3] = (b >> 4) & 1;
    bits[i * 8 + 4] = (b >> 3) & 1;
    bits[i * 8 + 5] = (b >> 2) & 1;
    bits[i * 8 + 6] = (b >> 1) & 1;
    bits[i * 8 + 7] = b & 1;
  }
  return bits;
}

function classifyChars(s: string) {
  let alpha = 0, digit = 0, upper = 0, lower = 0, special = 0;
  for (const c of s) {
    if (/[a-zA-Z]/.test(c)) { alpha++; if (c === c.toUpperCase() && c !== c.toLowerCase()) upper++; else lower++; }
    else if (/[0-9]/.test(c)) digit++;
    else special++;
  }
  return { alpha, digit, upper, lower, special, total: s.length };
}

// NIST SP 800-22 Frequency-within-Block test — divides the bitstream into
// M-bit blocks and tests whether each block has ~50% ones. More robust than
// FIPS Monobit for catching short-window biases.
function nistFrequencyBlock(bits: number[]): { pass: boolean; chi2: number } {
  if (bits.length < 100) return { pass: false, chi2: 0 };
  const M = Math.max(20, Math.floor(bits.length / 100));
  const N = Math.floor(bits.length / M);
  if (N < 2) return { pass: false, chi2: 0 };
  let chi2 = 0;
  for (let i = 0; i < N; i++) {
    const ones = bits.slice(i * M, (i + 1) * M).reduce((a, b) => a + b, 0);
    const pi = ones / M;
    chi2 += (pi - 0.5) ** 2;
  }
  chi2 = 4 * M * chi2;
  // p-value approx via igamc — we just use a chi-squared with N degrees-of-freedom
  // threshold: pass if chi2 / N is roughly within [0.5, 2.0].
  const ratio = chi2 / N;
  return { pass: ratio >= 0.5 && ratio <= 2.0, chi2: Math.round(chi2 * 100) / 100 };
}

// Autocorrelation lag-1 over a normalized byte stream of the token sequence.
// High autocorrelation (|r| > 0.3) suggests one token predicts the next —
// classic broken-RNG smell.
function autocorrelationLag1(values: number[]): number {
  if (values.length < 4) return 0;
  const n = values.length;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  let num = 0, den = 0;
  for (let i = 0; i < n - 1; i++) {
    num += (values[i] - mean) * (values[i + 1] - mean);
  }
  for (let i = 0; i < n; i++) {
    den += (values[i] - mean) ** 2;
  }
  return den === 0 ? 0 : Math.round((num / den) * 1000) / 1000;
}

export function Tokens() {
  const [tokens, setTokens] = useState('');
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [tab, setTab] = useState<'summary' | 'distribution' | 'fips' | 'bits'>('summary');
  const { pendingSendTo, clearSendTo } = useAppStore();

  useEffect(() => {
    if (pendingSendTo?.tool === 'sequencer') {
      const raw = pendingSendTo.responseRaw || pendingSendTo.requestRaw || '';
      const cookieMatches = raw.match(/(?:Set-Cookie|Cookie):\s*[^=]+=([^;\n]+)/gi) || [];
      const tokenValues = cookieMatches.map(m => m.split('=').slice(1).join('=').split(';')[0].trim()).filter(Boolean);
      if (tokenValues.length > 0) {
        setTokens(prev => prev ? prev + '\n' + tokenValues.join('\n') : tokenValues.join('\n'));
      } else {
        setTokens(prev => prev ? prev + '\n' + pendingSendTo.url : pendingSendTo.url);
      }
      clearSendTo();
    }
  }, [pendingSendTo, clearSendTo]);

  const analyze = useCallback(() => {
    const lines = tokens.split('\n').filter(Boolean);
    if (lines.length < 2) return;

    const allChars = lines.join('');
    const charSet = new Set(allChars);
    const avgLen = allChars.length / lines.length;

    const entropy = shannonEntropy(allChars);
    const maxEntropy = Math.log2(charSet.size);
    const normalized = maxEntropy > 0 ? (entropy / maxEntropy) * 100 : 0;

    const freq: Record<string, number> = {};
    for (const c of allChars) freq[c] = (freq[c] || 0) + 1;
    const expectedFreq = allChars.length / charSet.size;
    const charDistribution = Object.entries(freq)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 32)
      .map(([char, f]) => ({ char, freq: f, expected: expectedFreq }));

    const maxLen = Math.max(...lines.map(l => l.length));
    const bitAnalysis: number[] = [];
    for (let pos = 0; pos < Math.min(maxLen, 64); pos++) {
      const chars = lines.map(l => l[pos]).filter(Boolean);
      if (chars.length > 1) {
        bitAnalysis.push(shannonEntropy(chars.join('')));
      }
    }

    // v0.3.16: detect encoding so non-hex tokens (Base64, Base64URL, raw)
    // also get real bit-level analysis instead of silently being clamped to
    // hex characters only.
    const encoding = detectEncoding(allChars);
    const bits = stringToBits(allChars, encoding);

    const unique = new Set(lines);
    const duplicates = lines.length - unique.size;

    // Practical entropy = log2(unique tokens). Burp Sequencer calls this
    // "effective entropy" — it's a more honest number than character-level
    // entropy because it ignores formatting and counts real distinct values.
    const effectiveBits = unique.size > 0 ? Math.log2(unique.size) : 0;
    const predictedKeyspaceBits = charSet.size > 0 && avgLen > 0
      ? Math.log2(charSet.size) * avgLen
      : 0;

    const charClasses = classifyChars(allChars);

    // Autocorrelation across the byte stream of concatenated tokens —
    // catches PRNG-leak patterns where seq[i+1] depends on seq[i].
    const autocorrLag1 = autocorrelationLag1(Array.from(new TextEncoder().encode(allChars)));

    const nistFreqBlock = nistFrequencyBlock(bits);

    setResult({
      entropy: normalized,
      rating: normalized > 90 ? 'Excellent' : normalized > 70 ? 'Reasonable' : normalized > 40 ? 'Poor' : 'Critical',
      tokenCount: lines.length,
      avgLength: Math.round(avgLen),
      uniqueChars: charSet.size,
      charDistribution,
      bitAnalysis,
      fipsMonobit: bits.length > 100 ? fipsMonobit(bits) : { pass: false, ones: 0, total: 0 },
      fipsPoker: bits.length > 100 ? fipsPoker(bits) : { pass: false, chi2: 0 },
      fipsRuns: bits.length > 100 ? fipsRuns(bits) : { pass: false, runs: 0 },
      fipsLongRun: bits.length > 100 ? fipsLongRun(bits) : { pass: false, longest: 0 },
      duplicates,
      collisionRate: duplicates / lines.length * 100,
      encoding,
      effectiveBits: Math.round(effectiveBits * 10) / 10,
      predictedKeyspaceBits: Math.round(predictedKeyspaceBits * 10) / 10,
      charClasses,
      autocorrLag1,
      nistFreqBlock,
    });
    setTab('summary');
  }, [tokens]);

  const generateSample = () => {
    const sample = Array.from({ length: 20 }, () =>
      Array.from({ length: 32 }, () => Math.floor(Math.random() * 16).toString(16)).join('')
    ).join('\n');
    setTokens(sample);
  };

  const rc = (r: string) => r === 'Excellent' ? 'var(--green)' : r === 'Reasonable' ? '#eab308' : r === 'Poor' ? '#f0c040' : 'var(--red)';

  return (
    <div className="tokens">
      <div className="tokens-toolbar">
        <KeyRound size={14} />
        <span className="tokens-toolbar-title">Sequencer</span>
        <div style={{ flex: 1 }} />
        <button className="tokens-btn" onClick={generateSample}>Generate Sample</button>
        <button className="tokens-btn" onClick={() => { setTokens(''); setResult(null); }}><Trash2 size={10} /> Clear</button>
        <button className="tokens-btn primary" onClick={analyze} disabled={tokens.split('\n').filter(Boolean).length < 2}>
          <BarChart3 size={10} /> Analyze
        </button>
      </div>

      <div className="tokens-body">
        <div className="tokens-input-panel">
          <div className="tokens-input-header">
            Tokens (one per line)
            <span>{tokens.split('\n').filter(Boolean).length} loaded</span>
          </div>
          <textarea className="tokens-textarea" value={tokens} onChange={e => setTokens(e.target.value)}
            placeholder={"Paste session tokens, CSRF tokens, or other values here...\n\na1b2c3d4e5f6789012345\nf9e8d7c6b5a4321098765\n3c4d5e6f7a8b901234567\n..."} spellCheck={false} />
        </div>

        <div className="tokens-results-panel">
          {result ? (
            <>
              <div className="tokens-result-tabs">
                {(['summary', 'distribution', 'fips', 'bits'] as const).map(t => (
                  <button key={t} className={`tokens-result-tab ${tab === t ? 'active' : ''}`} onClick={() => setTab(t)}>
                    {t === 'summary' ? 'Summary' : t === 'distribution' ? 'Distribution' : t === 'fips' ? 'FIPS Tests' : 'Bit Analysis'}
                  </button>
                ))}
              </div>

              {tab === 'summary' && (
                <div className="tokens-summary">
                  <div className="tokens-score">
                    <div className="tokens-score-value" style={{ color: rc(result.rating) }}>
                      {Math.round(result.entropy)}%
                    </div>
                    <div className="tokens-score-label">Effective Entropy</div>
                    <div className="tokens-score-rating" style={{ color: rc(result.rating) }}>
                      {result.rating}
                    </div>
                  </div>
                  <div className="tokens-stats">
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.tokenCount}</div><div className="tokens-stat-label">Tokens</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.avgLength}</div><div className="tokens-stat-label">Avg Length</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.uniqueChars}</div><div className="tokens-stat-label">Unique Chars</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.duplicates}</div><div className="tokens-stat-label">Duplicates</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.collisionRate.toFixed(1)}%</div><div className="tokens-stat-label">Collision Rate</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.effectiveBits} bits</div><div className="tokens-stat-label">Effective Entropy</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.predictedKeyspaceBits} bits</div><div className="tokens-stat-label">Keyspace (theoretical)</div></div>
                    <div className="tokens-stat"><div className="tokens-stat-value">{result.encoding}</div><div className="tokens-stat-label">Encoding</div></div>
                    <div
                      className="tokens-stat"
                      style={{ color: Math.abs(result.autocorrLag1) > 0.3 ? 'var(--red)' : Math.abs(result.autocorrLag1) > 0.15 ? '#eab308' : 'var(--green)' }}
                      title="Lag-1 autocorrelation: |r| > 0.3 = strong sequential dependence (broken RNG)"
                    >
                      <div className="tokens-stat-value">{result.autocorrLag1.toFixed(3)}</div>
                      <div className="tokens-stat-label">Autocorrelation (lag-1)</div>
                    </div>
                  </div>
                  <div style={{ marginTop: 12, fontSize: 10, color: 'var(--text-3)', display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                    <span>Char classes:</span>
                    <span>alpha {result.charClasses.alpha}</span>
                    <span>digit {result.charClasses.digit}</span>
                    <span>upper {result.charClasses.upper}</span>
                    <span>lower {result.charClasses.lower}</span>
                    <span>special {result.charClasses.special}</span>
                  </div>
                </div>
              )}

              {tab === 'distribution' && (
                <div className="tokens-distribution">
                  <div className="tokens-chart">
                    {result.charDistribution.map((d, i) => (
                      <div key={i} className="tokens-bar-wrap" title={`'${d.char}': ${d.freq} (expected: ${Math.round(d.expected)})`}>
                        <div className="tokens-bar" style={{ height: `${(d.freq / result.charDistribution[0].freq) * 100}%` }} />
                        <span className="tokens-bar-label">{d.char}</span>
                      </div>
                    ))}
                  </div>
                  <div className="tokens-dist-expected">
                    <div className="tokens-dist-line" />
                    <span>Expected uniform frequency</span>
                  </div>
                </div>
              )}

              {tab === 'fips' && (
                <div className="tokens-fips">
                  {[
                    { name: 'FIPS 140-2 Monobit', result: result.fipsMonobit, detail: `${result.fipsMonobit.ones} ones / ${result.fipsMonobit.total} bits` },
                    { name: 'FIPS 140-2 Poker', result: result.fipsPoker, detail: `χ² = ${result.fipsPoker.chi2}` },
                    { name: 'FIPS 140-2 Runs', result: result.fipsRuns, detail: `${result.fipsRuns.runs} runs` },
                    { name: 'FIPS 140-2 Long Run', result: result.fipsLongRun, detail: `longest = ${result.fipsLongRun.longest}` },
                    { name: 'NIST SP 800-22 Freq-Block', result: result.nistFreqBlock, detail: `χ² = ${result.nistFreqBlock.chi2}` },
                  ].map(test => (
                    <div key={test.name} className={`tokens-fips-row ${test.result.pass ? 'pass' : 'fail'}`}>
                      {test.result.pass ? <CheckCircle size={12} /> : <XCircle size={12} />}
                      <span className="tokens-fips-name">{test.name}</span>
                      <span className="tokens-fips-detail">{test.detail}</span>
                      <span className="tokens-fips-badge">{test.result.pass ? 'PASS' : 'FAIL'}</span>
                    </div>
                  ))}
                  <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 8, padding: '6px 8px', background: 'var(--bg-0)', borderRadius: 6 }}>
                    Detected encoding: <strong style={{ color: 'var(--text-1)' }}>{result.encoding}</strong> — bit-level tests run on
                    {result.encoding === 'hex' ? ' 4 bits per hex char.' :
                     result.encoding === 'base64' || result.encoding === 'base64url' ? ' decoded byte stream (8 bits each).' :
                     ' UTF-8 byte stream — interpret cautiously, your tokens are not a standard encoding.'}
                  </div>
                </div>
              )}

              {tab === 'bits' && (
                <div className="tokens-bit-analysis">
                  <div className="tokens-bit-header">Per-Position Entropy (bits)</div>
                  <div className="tokens-bit-chart">
                    {result.bitAnalysis.map((e, i) => (
                      <div key={i} className="tokens-bit-bar-wrap" title={`Position ${i}: ${e.toFixed(2)} bits`}>
                        <div className="tokens-bit-bar" style={{ height: `${Math.min(e / 4 * 100, 100)}%`, background: e > 3 ? 'var(--green)' : e > 2 ? '#eab308' : 'var(--red)' }} />
                        <span className="tokens-bit-pos">{i}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="tokens-empty">
              <KeyRound size={28} strokeWidth={1} />
              <p>Paste tokens and analyze</p>
              <span>Supports Shannon entropy, FIPS 140-2 tests, and per-position bit analysis</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
